#!/bin/sh

set -e

case "$1" in
    configure)
    
# create the scanner group if it isn't already there
	addgroup --quiet --system scanner

# ensure /var/lib/colord exists and has appropriate permissions
	mkdir -p /var/lib/colord
	chown -R colord:colord /var/lib/colord

# create colord user if it isn't already there
        adduser --system --group --home /var/lib/colord colord \
	    --gecos "colord colour management daemon"


	;;
esac	

#DEBHELPER#

exit 0
