#!/bin/sh

set -e

case "$1" in
    configure)
    
# create the scanner group if it isn't already there
	addgroup --quiet --system scanner

# create colord user if it isn't already there
        adduser --system --ingroup colord --home /var/lib/colord colord \
	    --group colord --gecos "colord colour management daemon"

# ensure /var/lib/colord has appropriate permissions
	chown -R colord:colord /var/lib/colord

	;;
esac	

#DEBHELPER#

exit 0
